name: Check Code Formatting

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade uv
          uv pip install --system black

      - name: Check code formatting
        run: |
          black --check .
