name: Check Code Formatting

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up the latest version of uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: |
          uv venv -p 3.13
          uv pip install black

      - name: Check code formatting
        run: |
          uv run black --check .

      - name: Install bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Check bun version
        run: |
          bun -v
