name: Workflow

on: [push, pull_request]

jobs:
  cmake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: CMake - Configure & Build
        uses: threeal/cmake-action@main
        with:
          generator: Ninja

      - name: Install the package
        run: cmake --install build --prefix package

      - name: Run the executable
        run: ./package/bin/main

      - name: Archive the package
        run: tar -czvf package.tar.gz package/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: package.tar.gz
