name: Workflow

on: [push, pull_request]

jobs:
  cmake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: CMake - Configure & Build
        uses: threeal/cmake-action@main

      - name: Run executable
        run: ./build/main
