name: Workflow

on: [push, pull_request]

jobs:
  cmake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Configure CMake
        run: cmake -S . -B build -G "Ninja Multi-Config -DINSTALL_GTEST=OFF"

      - name: Build and run the tests (Debug mode)
        run: |
          cmake --build build --config Debug --target main_test
          ctest --test-dir build -C Debug --output-on-failure

      - name: Build the package (Release mode)
        run: cmake --build build --config Release --target func

      - name: Install the package
        run: cmake --install build --config Release --prefix package

      - name: Archive the package
        run: tar -czvf package.tar.gz package/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: package.tar.gz
