name: Workflow

on: [push, pull_request]

jobs:
  cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      # - name: Configure, build, and test
      #   run: |
      #     cmake -S . -B build -G "Ninja Multi-Config" -DINSTALL_GTEST=OFF
      #     cmake --build build --config Debug --target main_test
      #     ctest --test-dir build -C Debug --output-on-failure
      #     cmake --build build --config Release --target func
      #     cmake --install build --config Release --prefix package
