name: Workflow

on: [push, pull_request]

jobs:
  cmake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ninja
        run: sudo apt-get update && sudo apt-get install -y ninja-build

      - name: Setup cmake
        uses: threeal/cmake-action@main
