name: Workflow

on: [push, pull_request]

jobs:
  cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Configure and build
        run: |
          cmake -S . -B build -G "Ninja Multi-Config" -DINSTALL_GTEST=OFF
          cmake --build build --config Debug --target main_test
          ctest --test-dir build -C Debug --output-on-failure
          cmake --build build --config Release --target func
          cmake --install build --config Release --prefix package

      - name: Archive and upload package
        run: |
          if [ $RUNNER_OS == 'Linux' ]; then
            tar -czvf package.tar.gz package/
            echo "package.tar.gz" >> upload.txt
          else
            powershell Compress-Archive -Path package\* -DestinationPath package.zip
            echo "package.zip" >> upload.txt
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: package
          path: $(cat upload.txt)
