name: Workflow

on: [push, pull_request]

jobs:
  cmake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.30.x"

      - name: Configure the project
        run: cmake -B build -G Ninja

      - name: Build the project
        run: cmake --build build
